name: PR Build

on:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  RG_NAME: 'twt-web-${{ github.event.pull_request.number}}'
  LOCATION: 'eastus'
  WEBAPP_NAME: 'twt-ado40-pr-${{ github.event.pull_request.number}}'

jobs:

  buildImage:
    name: Build and Push Docker Image
    runs-on: self-hosted

    steps:

    # checkout code
    - name: checkout branch
      uses: actions/checkout@v2

    # authenticate into Azure Container Registry
    - name: "docker login"
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.CONTAINER_REGISTRY }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    # Build and push container image
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.CONTAINER_REGISTRY }}/tailwindtraders-ado40:${{ github.sha }}
        context: ./TailwindTraders.Website/Source/Tailwind.Traders.Web/

  deployInfra:
    runs-on: self-hosted
    needs: buildImage
    environment:
      name: Dev
      url: 'https://${{ env.WEBAPP_NAME }}.azurewebsites.net'
    steps:
      # checkout branch
      - name: git checkout main branch
        uses: actions/checkout@v2

      # log into Azure
      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy website to Azure
      - name: "Deploy Website"
        run: |
          az deployment sub create --name ${{ env.RG_NAME }} \
          --location ${{ env.LOCATION }} \
          --template-file ./main.bicep \
          --parameters location=${{ env.LOCATION }} \
          --parameters rgName=${{ env.RG_NAME }} \
          --parameters webAppName=${{ env.WEBAPP_NAME}} \
          --parameters dockerRegistryHost=${{ secrets.CONTAINER_REGISTRY }} \
          --parameters dockerRegistryServerUsername=${{ secrets.REGISTRY_USERNAME }} \
          --parameters dockerRegistryServerPassword=${{ secrets.REGISTRY_PASSWORD }} \
          --parameters dockerImage=tailwindtraders-ado40:${{ github.sha }}
        working-directory: ./TailwindTraders.Website/Deploy

      - name: Azure Logout
        run: |
          az logout
          az cache purge
          az account clear
