name: Build and Security Scan on PR

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  analyse:
    name: Analyse
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@master

    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      # Override language selection by uncommenting this and choosing your languages
      # with:
      #   languages: go, javascript, csharp, python, cpp, java

    # Autobuild attempts to build any compiled languages  (C/C++, C#, or Java).
    # If this step fails, then you should remove it and run the build manually (see below)
    - name: Autobuild
      uses: github/codeql-action/autobuild@v1

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1

    # - name: "Secret Scanner"
    #   uses: max/secret-scan@master

  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@master

    - name: Docker build
      working-directory: Source/Tailwind.Traders.Web
      run: |
        docker build . --build-arg sdkTag=5.0 --build-arg runtimeTag=5.0 -t ${{ secrets.CONTAINER_REGISTRY }}/tailwindtraders/web:gh-${{ github.sha }}
    
    - name: Scan Image for Vulnerabilities
      uses: Azure/container-scan@releases/v1
      id: container-scan
      continue-on-error: true
      with:
        image-name: ${{ secrets.CONTAINER_REGISTRY }}/tailwindtraders/web:gh-${{ github.sha }}
    
    - name: Post logs to appinsights
      uses: Azure/publish-security-assessments@v0
      with:
        scan-results-path: ${{steps.container-scan.outputs.scan-report-path}}
        connection-string: ${{ secrets.AZ_APPINSIGHTS_CONNECTION_STRING }}
        subscription-token: ${{ secrets.AZ_SUBSCRIPTION_TOKEN }}

    # - name: Notify dedicated teams channel
    #   uses: jdcargile/ms-teams-notification@v1.3
    #   with:
    #     github-token: ${{ github.token }} # this will use the runner's token.
    #     ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
    #     notification-summary: Your custom notification message 
    #     notification-color: 17a2b8
    #     timezone: America/Los_Angeles
