name: Tailwind Traders Website Build

on:
  push:
    branches: [main, ]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    name: Build and Scan for Vulnerabilities
    runs-on: ubuntu-latest
    # needs: analyse
    steps:
    - name: Checkout Github Action
      uses: actions/checkout@master

    - name: Docker login
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.CONTAINER_REGISTRY }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Docker build
      working-directory: Source/Tailwind.Traders.Web
      run: |
        docker build . --build-arg sdkTag=5.0 --build-arg runtimeTag=5.0 -t ${{ secrets.CONTAINER_REGISTRY }}/tt-web:gh-${{ github.sha }}

    - name: Docker push
      run: |
        docker push ${{ secrets.CONTAINER_REGISTRY }}/tt-web:gh-${{ github.sha }}
